version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"


  green:
    image: "hoiae/foreco.backend"
    ports:
      - "8080:8080"  # green은 8080 포트를 열어줍니다.
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DYNAMO_ACCESS: ${DYNAMO_ACCESS}
      DYNAMO_SECRET: ${DYNAMO_SECRET}
      S3_ACCESS: ${S3_ACCESS}
      S3_BUCKET: ${S3_BUCKET}
      S3_SECRET: ${S3_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      EC2_HOST: ${EC2_HOST}
      AI_URL: ${AI_URL}
      AI_MISSION_URL: ${AI_MISSION_URL}
    depends_on:
      - redis
    links:
      - redis

  blue:
    image: "hoiae/foreco.backend"
    ports:
      - "8081:8080"  #blue는 8081 포트를 열어줍니다.
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DYNAMO_ACCESS: ${DYNAMO_ACCESS}
      DYNAMO_SECRET: ${DYNAMO_SECRET}
      S3_ACCESS: ${S3_ACCESS}
      S3_BUCKET: ${S3_BUCKET}
      S3_SECRET: ${S3_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      EC2_HOST: ${EC2_HOST}
      AI_URL: ${AI_URL}
      AI_MISSION_URL: ${AI_MISSION_URL}

    depends_on:
      - redis
    links:
      - redis