version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"

  green:
    container_name: green
    image: leeseolhui/ibajee-web
    platform: linux/arm64
    expose:
      - 8080
    ports:
      - 8080:8080  # green은 8080 포트를 열어줍니다.
    env_file:
      - ./.env
    depends_on:
      - redis
    links:
      - redis

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - green
    volumes:
      - ./nginx/certificates:/nginx/certificates
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf