version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"

  green:
    image: ibajee-web
    ports:
      - 8080:8080  # green은 8080 포트를 열어줍니다.
    env_file:
      - ./.env
    depends_on:
      - redis
    links:
      - redis

  blue:
    image: ibajee-web
    ports:
      - 8081:8080  #blue는 8081 포트를 열어줍니다.
    env_file:
      - ./.env
    depends_on:
      - redis
    links:
      - redis