name: Java CI with Gradle

on:
  release:
    types: [push] # push를 하면 자동으로 실행
  push:
    branches: [develop] # master 브랜치에서 동작

jobs:
  build:
  
    runs-on: ubuntu-latest # 스크립트를 작동할 OS
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
          character set server: 'utf8'
          mysql database: ${{secrets.DB_NAME}}
          mysql user: ${{secrets.DB_USERNAME}}
          mysql password: ${{secrets.DB_PASSWORD}}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    # ./gradlw 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    # 프로젝트 build
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


